# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "7.0"

target "BiP" do
    pod 'Reachability', '~> 3.1'
    pod "youtube-ios-player-helper", "~> 0.1.1"
    pod 'YTVimeoExtractor'
    pod 'PBJVision'
    pod 'AWSS3'
    pod 'AWSCognito'
    pod 'AWSCognitoSync'
end

target "BiPTests" do

end

